name: Auto-Save RSVP Mj-Shops
on:
  repository_dispatch:
    types: [simpan-ucapan]

jobs:
  save:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Update Database
        run: |
          # Ambil nama project buat jadi nama folder
          ID="${{ github.event.client_payload.project_id }}"
          # Bikin foldernya kalau belum ada
          mkdir -p "database/${ID}"
          
          # Bikin nama file unik pake timestamp biar gak bentrok
          TS=$(date +%s)
          FILE="database/${ID}/ucapan-${TS}.json"
          
          # Simpan data kiriman ke file json baru
          echo '${{ toJson(github.event.client_payload.data) }}' > "$FILE"
          
      - name: Commit & Push
        run: |
          git config --global user.name "Mj-Shops-Bot"
          git config --global user.email "hamudi2012@gmail.com"
          git add database/
          git commit -m "RSVP Baru di folder ${{ github.event.client_payload.project_id }}"
          git push
