name: Auto Update JSON Photos
on:
  push:
    paths:
      - 'public/photo/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate JSON
        run: |
          echo "{" > daftar-foto.json
          echo "  \"baseUrl\": \"https://mj-shops.biz.id/public/photo/\"," >> daftar-foto.json
          echo "  \"photos\": [" >> daftar-foto.json
          find public/photo -maxdepth 1 -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.gif" \) -exec basename {} \; | sed 's/.*/    "&",/' | sed '$ s/,$//' >> daftar-foto.json
          echo "  ]" >> daftar-foto.json
          echo "}" >> daftar-foto.json

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add daftar-foto.json
          git commit -m "Otomatis update daftar-foto.json [skip ci]" || exit 0
          git push origin main
          
